import { Company, CacheProvider, Server, Allocation, CompanyType, StatusType } from './types';

// Mock Companies Data
export const mockCompanies: Company[] = [
  // ISPs (1 to 3, then 7, then 39 to 91)
  {
    id: 'comp-001',
    name: 'Antaranga Dot Com Limited',
    type: CompanyType.ISP,
    email: 'info@antaranga.com',
    address: 'Shaan Tower (3rd Floor), Chamelibag, Shantinagar, Chowrasta, Dhaka',
    status: StatusType.ACTIVE,
    createdAt: new Date('2018-07-02'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-002',
    name: 'Amber IT Limited',
    type: CompanyType.ISP,
    email: 'info@amberit.com.bd',
    address: 'Navana Tower (7th floor), 45 Gulshan South C/A, Circle-1, Dhaka-1212.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2023-07-02'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-003',
    name: 'Alo Communication Ltd',
    type: CompanyType.ISP,
    email: 'contact@alocommunications.com',
    address: '45, Navana Tower, 14th floor Gulshan Circle1, Dhaka 1212.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2023-07-02'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-004',
    name: 'Bangladesh Telecommunications Company Limited',
    type: CompanyType.IIG,
    email: 'info@btcl.gov.bd',
    address: 'Telejogajog Bhaban 37/E, Eskaton Garden, Dhaka-1000, Bangladesh',
    status: StatusType.ACTIVE,
    createdAt: new Date('2008-03-20'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-005',
    name: 'Mango Teleservices Limited',
    type: CompanyType.IIG,
    email: 'contact@mango.com.bd',
    address: '82 Mohakhali C/A (12th floor), Dhaka-1212, Bangladesh',
    status: StatusType.ACTIVE,
    createdAt: new Date('2008-02-25'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-006',
    name: 'Maxnet Online',
    type: CompanyType.IIG,
    email: 'support@maxnetbd.com',
    address: 'Aqua Tower (Level-3), Bir Uttam A. K. Khandakar Road, 43, Mohakhali C/A, Dhaka-1212.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-007',
    name: 'Link-3 Technologies Limited',
    type: CompanyType.ISP,
    email: 'info@link3.net',
    address: 'Police Plaza Concord, Tower-01, 13th Floor, Plot-2, Road-144, Gulshan Model Town, Dhaka-1212',
    status: StatusType.ACTIVE,
    createdAt: new Date('2023-09-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-008',
    name: 'I-TEL Limited',
    type: CompanyType.IIG,
    email: 'info@i-tel.com',
    address: 'Suite-H, Road-37, House 39, Gulshan-2, Dhaka-1212',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-009',
    name: 'Global Fair Communications Limited',
    type: CompanyType.IIG,
    email: 'contact@globalfairbd.com',
    address: 'Red Crescent Borak Tower (Level-7), 71-72 Old Elephant Road, Eskaton Graden, Dhaka-1000.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-010',
    name: 'Level-3 Carrier Limited',
    type: CompanyType.IIG,
    email: 'noc@level3bd.com',
    address: '26, Green Corner, Green Road, Dhaka-1205.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-011',
    name: 'Windstrem Communication Limited',
    type: CompanyType.IIG,
    email: 'info@windstream-bd.com',
    address: 'Chandrashila Suvastu Tower (10th & 11th Floor), 69/1, Green Road, Panthapath, Dhaka-1205',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-012',
    name: 'BD Hub Limited',
    type: CompanyType.IIG,
    email: 'contact@bdhub.com',
    address: 'Tower (7th Floor), Circle-1,Gulshan, Dhaka-1212',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-013',
    name: '1Asia Alliance Communication Limited',
    type: CompanyType.IIG,
    email: 'info@1asiabd.com',
    address: 'House- 4/3, Block A Lalmatia, Dhaka 1207',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-014',
    name: 'Fiber@Home Global Limited',
    type: CompanyType.IIG,
    email: 'iig-support@fiberathome.net',
    address: '69/K Bir Uttom Kazi Nurruzzaman Road (Green Road), Panthapath, Dhaka-1205',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-015',
    name: 'Bangladesh Submarine Cable Company Limited',
    type: CompanyType.IIG,
    email: 'info@bsccl.com',
    address: 'Telejogajog Bhaban(6th Floor), 37/E, Eskaton Garden, Dhaka- 1000',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-016',
    name: 'Greenmax Technologies Limited',
    type: CompanyType.IIG,
    email: 'info@greenmaxbd.com',
    address: '26 Shyamoli, Bir Uttom AW Chowdhury Road, Dhaka-1207',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-017',
    name: 'Radiant Communications Limited',
    type: CompanyType.IIG,
    email: 'info@radiantbd.com',
    address: 'Suite# A3-4 & D3-4, House No.# 15, Road No. #17, Kemal Ataturk Avenue, Banani, Dhaka-1213',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-018',
    name: 'Rego Communications Limited',
    type: CompanyType.IIG,
    email: 'contact@regobd.com',
    address: 'H-43, R-2A, Dhanmondi, Dhaka- 1209',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-019',
    name: 'Planet Internet Gateway Limited',
    type: CompanyType.IIG,
    email: 'info@planetbd.com',
    address: 'House No. 91, Flat No. A-1, Road No. 7A, Dhanmondi R/A, Dhaka.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-020',
    name: 'Peerex Networks Limited',
    type: CompanyType.IIG,
    email: 'info@peerex.net',
    address: 'Suite# B3-4, House No. 15, Road No. 17, Kemal Ataturk Avenue, Banani, Dhaka-1213',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-021',
    name: 'Summit Communications Limited',
    type: CompanyType.IIG,
    email: 'iig@summitcommunications.net',
    address: '18 Kawran Bazar C/A, Dhaka-1215',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-022',
    name: 'Toron Limited',
    type: CompanyType.IIG,
    email: 'info@toronbd.com',
    address: 'House No. 52, Road No. 3/A, Dhanmondi R/A, Dhaka-1209',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-023',
    name: 'Max Hub Limited',
    type: CompanyType.IIG,
    email: 'support@maxhubbd.com',
    address: 'H-90, R-23, B-A, Banani, Dhaka 1213',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-024',
    name: 'Aamra Technologies Limited',
    type: CompanyType.IIG,
    email: 'info.technologies@aamra.com.bd',
    address: 'Faruque Rupayun Tower (9th Floor) 32 Kemal Ataturk Avenue, Banani C/A, Dhaka 1213',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-025',
    name: 'Intraglobe Communications Limited',
    type: CompanyType.IIG,
    email: 'contact@intraglobebd.com',
    address: 'Suite# 802, Concord Tower, 113 Kazi Nazrul Islam Avenue, Dhaka-1000',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-026',
    name: 'Startrek Telecom Limited',
    type: CompanyType.IIG,
    email: 'info@startrekbd.com',
    address: '10 Kemal Ataturk Banani Dhaka',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-027',
    name: 'Cybergate Limited',
    type: CompanyType.IIG,
    email: 'info@cybergatebd.com',
    address: '20th Floor, Blue Ocean Tower, 40 Kemal Ataturk Avenue, Banani C/C, Dhaka-1213',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-028',
    name: 'Delta Infocom Limited',
    type: CompanyType.IIG,
    email: 'info@deltainfocom.com',
    address: 'Nandani, H-58/CHA/1, West Rajabazar, Panthapath, Dhaka',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-029',
    name: 'Exabyte Limited',
    type: CompanyType.IIG,
    email: 'info@exabyte.com.bd',
    address: '73 Kakrail Eastern Commercial Complex, 8th Floor, Suite 702, Dhaka-1000',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-030',
    name: 'Sky Tel Communication Limited',
    type: CompanyType.IIG,
    email: 'info@skytelbd.com',
    address: '82 Mohakhali C/A, Dhaka- 1212',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-031',
    name: 'BD Link Communication Limited',
    type: CompanyType.IIG,
    email: 'info@bdlink.com',
    address: 'UTC Building, 8 Panthapath, Level-22, Dhaka-1215',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-032',
    name: 'ADN International Gateway Limited',
    type: CompanyType.IIG,
    email: 'info@adnsl.com',
    address: '17, Red Crecent, Concord Tower(5th floor), Bir Uttam A K Khandakar Road, Mohakhali C/A, Dhaka-1212',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-033',
    name: 'Equitel Communication Limited',
    type: CompanyType.IIG,
    email: 'info@equitelbd.com',
    address: 'Plot-68(old 45), Block-H, Road-11, Banani, Dhaka',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-034',
    name: 'Velocity Networks Limited',
    type: CompanyType.IIG,
    email: 'contact@velocitynetworks.com',
    address: 'Lotus Kamal Tower-one, level-9, 57 Zoar Shahara C/A, Dhaka-1229',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-035',
    name: 'Earth Telecommunication (PVT) Limited',
    type: CompanyType.IIG,
    email: 'info@earthtelecombd.com',
    address: '17/1 Arjot Para, Mohakhali, Tejgaon, Dhaka-1215.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-036',
    name: 'NovoCom Limited',
    type: CompanyType.IIG,
    email: 'info@novocom-bd.com',
    address: 'Konabari, Neelnagar, Gazipur',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-037',
    name: 'Coronet Corporation Limited',
    type: CompanyType.IIG,
    email: 'info@coronetbd.com',
    address: '30, Shahjal Avenue, Sector-4, Uttara, Dhaka-1230',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-04-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-038',
    name: 'Virgo Communications Limited',
    type: CompanyType.IIG,
    email: 'info@virgobd.com',
    address: 'H#178, R#02, DOHS, Baridhara, Dhaka-1206.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2013-01-17'),
    updatedAt: new Date('2024-06-12'),
  },
  // Nationwide ISPs (comp-039 to comp-091)
  {
    id: 'comp-039',
    name: 'Agni Systems Limited',
    type: CompanyType.ISP,
    email: 'info@agni.com',
    address: '45 Navana Tower, 11th Floor, Suit-A, Gulshan Avenue, Gulshan-1, Dhaka-1212',
    status: StatusType.ACTIVE,
    createdAt: new Date('2023-03-04'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-040',
    name: 'One Sky Communication Limited',
    type: CompanyType.ISP,
    email: 'info@oneskybd.com',
    address: '115/23,SA Bhaban, (5th Flor), Motijheel Circular Road, Dhaka-1000',
    status: StatusType.ACTIVE,
    createdAt: new Date('2024-01-28'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-041',
    name: 'Blue Net Communication JV Ltd',
    type: CompanyType.ISP,
    email: 'info@bluenetbd.com',
    address: 'Level 17, Rupayan Shelford, 23/6 Mirpur Road, Shyamoli, Dhaka-1207.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2019-10-13'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-042',
    name: 'Ranks ITT Limited',
    type: CompanyType.ISP,
    email: 'info@ranksitt.net',
    address: '117/A (Level-3), Old Airport Road, Bijoy Sharani, Tejgaon, Dhaka-1215.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2023-09-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-043',
    name: 'X-Press Technologies Limited',
    type: CompanyType.ISP,
    email: 'info@x-pressbd.com',
    address: '121/1/A, South Kamalapur (Ground Floor) Motijheel, Dhaka',
    status: StatusType.ACTIVE,
    createdAt: new Date('2021-06-28'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-044',
    name: 'Telnet Communication Limited',
    type: CompanyType.ISP,
    email: 'info@telnetbd.com',
    address: 'Genetic Plaza, (2nd floor) House # 16, Shak Kamal Shoroni,Road # 16, Dhanmondi, Dhaka-1209,',
    status: StatusType.ACTIVE,
    createdAt: new Date('2022-02-28'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-045',
    name: 'Access Telecom (BD) Limited',
    type: CompanyType.ISP,
    email: 'info@accesstel.net',
    address: 'Suit#.901, Concord Tower, 113, Kazi Nazrul Islam Avenue, Dhaka-1000.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2020-05-01'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-046',
    name: 'ADN Telecom Limited',
    type: CompanyType.ISP,
    email: 'info@adntelecom.com.bd',
    address: 'Red Crescent Concord Tower (19th Floor), 17, Mohakhali C/A, Dhaka-1212,',
    status: StatusType.ACTIVE,
    createdAt: new Date('2020-07-06'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-047',
    name: 'Systems Solutions & Development Technologies Ltd.',
    type: CompanyType.ISP,
    email: 'info@ssdtechbd.com',
    address: 'Highway Homes (2nd Floor), KA-32/6, Shajadpur, PragatiSharoni, Gulshan, Dhaka',
    status: StatusType.ACTIVE,
    createdAt: new Date('2024-03-23'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-048',
    name: 'Aamra Networks Limited',
    type: CompanyType.ISP,
    email: 'info.networks@aamra.com.bd',
    address: 'Safura Tower (12th floor), 20 Kemal Ataturk Avenue, Banani, Dhaka-1213',
    status: StatusType.ACTIVE,
    createdAt: new Date('2020-06-30'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-049',
    name: 'Bijoy Online Limited',
    type: CompanyType.ISP,
    email: 'info@bijoyonline.com',
    address: '52, Gulshan South Avenue, Silver Tower (15th Floor), Gushan-1, Dhaka-1212',
    status: StatusType.ACTIVE,
    createdAt: new Date('2018-11-11'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-050',
    name: 'IP Communications Limited',
    type: CompanyType.ISP,
    email: 'info@ipclbd.com',
    address: '3rd Floor, 44/9, Panthapath, North Dhanmondi, Dhaka.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2020-07-13'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-051',
    name: 'KS Network Limited',
    type: CompanyType.ISP,
    email: 'info@ksnetworkbd.com',
    address: 'Principle Park, 11/7/G, Free School Street, Kathal Bagan, Box Culvert Road, Dhaka-1205.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2021-02-23'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-052',
    name: 'Next Online Limited',
    type: CompanyType.ISP,
    email: 'info@nextonlinebd.com',
    address: 'H#23/1A, Road Noor Fatah Lane, Lalbag, Dhaka-1211',
    status: StatusType.ACTIVE,
    createdAt: new Date('2018-04-17'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-053',
    name: 'Royal Green Limited',
    type: CompanyType.ISP,
    email: 'info@royalgreenbd.com',
    address: '114, motijhil, c/a, level-11, dhaka-1000',
    status: StatusType.ACTIVE,
    createdAt: new Date('2020-07-06'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-054',
    name: 'Sheba Broadband Limited',
    type: CompanyType.ISP,
    email: 'info@shebabroadband.com',
    address: '5th Floor, house no. 55, Raoad no. 4/A, Dhanmondi, Dhaka-1209',
    status: StatusType.ACTIVE,
    createdAt: new Date('2021-06-16'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-055',
    name: 'Nreach-Net (Pvt.) Limited',
    type: CompanyType.ISP,
    email: 'info@nreachnet.com',
    address: 'Nitol Centre (14th Level), 71 Mohakhali C/A, Dhaka-1212',
    status: StatusType.ACTIVE,
    createdAt: new Date('2023-09-09'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-056',
    name: 'Optimax Communications Limited',
    type: CompanyType.ISP,
    email: 'info@optimaxbd.com',
    address: 'House-06,road-28,block-K,banani,dhaka-1213',
    status: StatusType.ACTIVE,
    createdAt: new Date('2019-09-29'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-057',
    name: 'Race Online Limited',
    type: CompanyType.ISP,
    email: 'info@race.com.bd',
    address: 'Khaza tower 9th floor, 95 Mohakhali C/A, Dhaka 1212',
    status: StatusType.ACTIVE,
    createdAt: new Date('2019-09-15'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-058',
    name: 'Circle Network',
    type: CompanyType.ISP,
    email: 'info@circlenetworkbd.com',
    address: 'Unity Trade Centre (3rd floor), Dendabar, Ashulia, Savar, Dhaka-1344.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2021-03-01'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-059',
    name: 'Infolink Limited',
    type: CompanyType.ISP,
    email: 'info@infolink.com.bd',
    address: 'Plot-56, Road-12, Block-j, Baridhara, Gulshan, Vatara, Dhaka-1212',
    status: StatusType.ACTIVE,
    createdAt: new Date('2023-05-08'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-060',
    name: 'Radiant Communications Limited (ISP)',
    type: CompanyType.ISP,
    email: 'isp@radiantbd.com',
    address: 'Suit- A3-4 & D3-4, House-15, Road-17, Kemal Ataturk Avenue, Banani, Dhaka',
    status: StatusType.ACTIVE,
    createdAt: new Date('2022-02-28'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-061',
    name: 'Innovative Online Limited',
    type: CompanyType.ISP,
    email: 'info@iolbd.net',
    address: 'Minar (2nd floor), 15 OR Nizam Road, Panchalaish, chattogram-4100.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2021-10-23'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-062',
    name: 'Tahoe Communications Limited',
    type: CompanyType.ISP,
    email: 'info@tahoebd.com',
    address: '242, Tejgaon I/A, Dhaka-1208',
    status: StatusType.ACTIVE,
    createdAt: new Date('2018-11-13'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-063',
    name: 'SpaceNet Limited',
    type: CompanyType.ISP,
    email: 'info@spacenetbd.com',
    address: 'Red crescent Borak Tower, Level-M, 37/3/A ,Eskaton Garden Road, Dhaka',
    status: StatusType.ACTIVE,
    createdAt: new Date('2018-07-02'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-064',
    name: 'Chittagong Data Communication',
    type: CompanyType.ISP,
    email: 'info@cdc-bd.com',
    address: 'Appolo Shoping Center, Shop-17, Kajir dewry, Kotoali, Chittagong.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2018-01-18'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-065',
    name: 'Business Network',
    type: CompanyType.ISP,
    email: 'info@businessnetworkbd.com',
    address: '40/2,Meradia, Khilgoan, Dhaka-1219',
    status: StatusType.ACTIVE,
    createdAt: new Date('2018-11-29'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-066',
    name: 'Nation Communication (AMR ISP)',
    type: CompanyType.ISP,
    email: 'info@nationcommbd.com',
    address: 'Flat-A3, House-120, Bankers Row, West Nakhal Para, Tejgaon, Dhaka-1215',
    status: StatusType.ACTIVE,
    createdAt: new Date('2023-08-11'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-067',
    name: 'BDCOM Online Limited',
    type: CompanyType.ISP,
    email: 'info@bdcom.com',
    address: 'JL Bhaban, House-01, Road-01, Gulshan Avenue, Gulshan-1, Dhaka-1212',
    status: StatusType.ACTIVE,
    createdAt: new Date('2021-11-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-068',
    name: 'Grameen CyberNet Limited',
    type: CompanyType.ISP,
    email: 'info@grameencybernet.com',
    address: 'RM Center (4th Floor), 101 Gulshan Avenue, Gulshan, Dhaka-1212',
    status: StatusType.ACTIVE,
    createdAt: new Date('2016-11-21'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-069',
    name: 'Cosmopolitan Communications Limited',
    type: CompanyType.ISP,
    email: 'info@cosmopolitanbd.com',
    address: 'H.A.K Tower, 3/C Kawran Bazar C/A, Dhaka-1215',
    status: StatusType.ACTIVE,
    createdAt: new Date('2021-12-05'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-070',
    name: 'Broadband Telecom Services Limited',
    type: CompanyType.ISP,
    email: 'info@broadbandtelecom.com',
    address: 'Ispahani Building (5th Floor), Sk. Mujib Road, Agrabad C/A, Chittaong-4100',
    status: StatusType.ACTIVE,
    createdAt: new Date('2021-11-20'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-071',
    name: 'SK Traders',
    type: CompanyType.ISP,
    email: 'info@sktradersbd.com',
    address: 'Dilara Tower (Level-7), Suite-7G-H, 77 Bir Uttam C. R. datta, 340 Shonargaon Road, Hatirpool, Dhaka-1205.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2021-11-15'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-072',
    name: 'Kloud Technologies Limited',
    type: CompanyType.ISP,
    email: 'info@kloudtech.com.bd',
    address: 'Level-04, Venture tower, Plot-03, Bir Uttam A.K Khandakar RoadMohakhali, C/A, Dhaka-1212.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2019-10-14'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-073',
    name: 'BRAC Net Limited',
    type: CompanyType.ISP,
    email: 'info@bracnet.net',
    address: 'Suit-603,(5th floor),Rob super market, Plot-22, Gulshan (north) commercial area,G Gulshan-2, Dhaka-1212',
    status: StatusType.ACTIVE,
    createdAt: new Date('2021-11-26'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-074',
    name: 'Plexus Cloud',
    type: CompanyType.ISP,
    email: 'info@plexuscloud.net',
    address: 'House-34, Road-1, Block-A, Banasree, Dhaka',
    status: StatusType.ACTIVE,
    createdAt: new Date('2023-06-20'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-075',
    name: 'Societe Internationale De Telacommunications Aeronautiques (SITA)',
    type: CompanyType.ISP,
    email: 'sita.dhaka@sita.aero',
    address: 'Jiban Biam Tower (11th Floor), 10 Dilkusha Commercial Area, Dhaka-1000',
    status: StatusType.ACTIVE,
    createdAt: new Date('2022-02-28'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-076',
    name: 'Square Informatix Limited',
    type: CompanyType.ISP,
    email: 'info@squareinformatix.com',
    address: '"Square Centre", 48, Mohakhali C/A, Dhaka-1212,',
    status: StatusType.ACTIVE,
    createdAt: new Date('2023-10-30'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-077',
    name: 'Dhaka Fiber Net Limited',
    type: CompanyType.ISP,
    email: 'info@dhakafibernet.com',
    address: '89/2, West Panthapath, Haque Chamber, Suit-10A, Dhaka',
    status: StatusType.ACTIVE,
    createdAt: new Date('2018-09-13'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-078',
    name: 'Pan M Tech Limited',
    type: CompanyType.ISP,
    email: 'info@panmtech.com',
    address: '43 Sonargoan Janapad Road, 4th floor, Flat-A/4, Sector 11, Uttara, Dhaka- 1230',
    status: StatusType.ACTIVE,
    createdAt: new Date('2018-12-18'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-079',
    name: 'SkyView Online Limited',
    type: CompanyType.ISP,
    email: 'info@skyviewonline.com.bd',
    address: 'Sky View Online Limited, 151/1, Shahid Faruqe Road Jatrabari, Dhaka-1204',
    status: StatusType.ACTIVE,
    createdAt: new Date('2023-08-06'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-080',
    name: 'Premium Connectivity Limited',
    type: CompanyType.ISP,
    email: 'info@premiumconnectivity.com',
    address: 'Cha-21/2, Uttar Badda, Dhaka',
    status: StatusType.ACTIVE,
    createdAt: new Date('2018-12-04'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-081',
    name: 'Drik ICT Limited',
    type: CompanyType.ISP,
    email: 'office@drikict.net',
    address: 'House 58, Road 15/A, Dhanmondi, Dhaka-1209 .',
    status: StatusType.ACTIVE,
    createdAt: new Date('2021-03-06'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-082',
    name: 'Inter Cloud Limited',
    type: CompanyType.ISP,
    email: 'info@intercloud.com.bd',
    address: 'House#50, Road#11, Block-F, Bir Uttam Khadimul Bashar Sarak, Banani, Dhaka-1213.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2018-03-11'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-083',
    name: 'Bangladesh Data Center Company Limited (BDDCL)',
    type: CompanyType.ISP,
    email: 'info@bddcl.gov.bd',
    address: 'E-14/X, ICT Tower (11th Floor), Agargaon, Dhaka.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2022-06-19'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-084',
    name: 'Bangladesh Export Import Company Limited',
    type: CompanyType.ISP,
    email: 'info@beximco.net',
    address: '17 Dhanmondi R/A, Road # 2, Dhaka-1205',
    status: StatusType.ACTIVE,
    createdAt: new Date('2019-09-01'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-085',
    name: 'Metro Net Bangladesh Limited',
    type: CompanyType.ISP,
    email: 'info@metronetbd.com',
    address: 'PBL Tower(13th floor), 17 (new) Gulshan North C/A, Dhaka-1212',
    status: StatusType.ACTIVE,
    createdAt: new Date('2017-10-28'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-086',
    name: 'Unified Core Ltd',
    type: CompanyType.ISP,
    email: 'info@unifiedcore.net',
    address: '44/7/A & 44/7/B ( 4th Floor), North Dhanmoddi (West Panthapath),Kalabagan, Dhaka-1205',
    status: StatusType.ACTIVE,
    createdAt: new Date('2023-04-23'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-087',
    name: 'Triangle Services Limited',
    type: CompanyType.ISP,
    email: 'info@triangle.com.bd',
    address: 'TA-131 (7th Floor), Wakil Tower, Badda Link Road, Gulshan-1, Dhaka-1212',
    status: StatusType.ACTIVE,
    createdAt: new Date('2021-12-26'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-088',
    name: 'Asia Pacific Communication Limited',
    type: CompanyType.ISP,
    email: 'info@apclbd.net',
    address: 'Siraj Tower (5th Floor), Ta-114/1, Bir Uttam AK Khandakar Road (Gulshan1-Badda Link Road), Middle Badda, Dhaka-1212',
    status: StatusType.ACTIVE,
    createdAt: new Date('2021-10-23'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-089',
    name: 'Zip Net Limited',
    type: CompanyType.ISP,
    email: 'info@zipnet.com.bd',
    address: '56 Purana Paltan Line, Eastern Trade Centre(9th Floor), Dhaka.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2020-05-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-090',
    name: 'DB Technologies',
    type: CompanyType.ISP,
    email: 'info@dbtech.com',
    address: 'Holding No-373/374 Tejgaon Industrial Area, Dhaka-1208',
    status: StatusType.ACTIVE,
    createdAt: new Date('2021-11-22'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-091',
    name: 'Aftab IT Limited',
    type: CompanyType.ISP,
    email: 'info@aftabit.com',
    address: 'Eastern Trade Center (14th floor), 56 Purana Paltan Line, Dhaka-1000, Bangladesh',
    status: StatusType.ACTIVE,
    createdAt: new Date('2019-04-01'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-092',
    name: 'Connect BD Limited',
    type: CompanyType.ISP,
    email: 'info@connectbd.com',
    address: 'Akash Plaza House -21, Room-602, Road-7/D, Sector-9, Uttara, Dhaka.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2021-06-29'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-093',
    name: 'ICC Communication Ltd.',
    type: CompanyType.ISP,
    email: 'info@icccommunications.com',
    address: 'Plot-15-18,Lane-6,Block-D,Pallabi,Mirpur-12,Dhaka-1216',
    status: StatusType.ACTIVE,
    createdAt: new Date('2023-11-15'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-094',
    name: 'Digi Jadoo Broadband Limited',
    type: CompanyType.ISP,
    email: 'info@digijadoo.com',
    address: 'Lotus Kamal Tower-1 (Level-9), 57 Joar Shahara C/A, Nikunja-2 New Airport Road, Dhaka.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2021-06-16'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-095',
    name: 'Bangla Trac Communications Limited',
    type: CompanyType.ISP,
    email: 'info@banglatrac.com',
    address: 'Plot-68 (Old-45), Block-H, Road-11, Banani, Dhaka-1213',
    status: StatusType.ACTIVE,
    createdAt: new Date('2022-12-30'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-096',
    name: 'Always On Network Bangladesh Limited',
    type: CompanyType.ISP,
    email: 'info@alwayson.com.bd',
    address: 'House- CWN(B)-6, Road No-36, Gulshan-2, Dhaka-1212',
    status: StatusType.ACTIVE,
    createdAt: new Date('2021-03-19'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-097',
    name: 'Trust Innovation Limited',
    type: CompanyType.ISP,
    email: 'info@trustinnovation.com.bd',
    address: 'CSD, Bhaban, Dhaka Cantonment, Dhaka-1206',
    status: StatusType.ACTIVE,
    createdAt: new Date('2020-06-29'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-098',
    name: 'Information Services Network Ltd.',
    type: CompanyType.ISP,
    email: 'info@isnbd.com',
    address: 'TMC Building (4th Floor) 52, New Eskaton Road, Dhaka-1000',
    status: StatusType.ACTIVE,
    createdAt: new Date('2018-02-19'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-099',
    name: 'BTS Communications (BD) Limited',
    type: CompanyType.ISP,
    email: 'info@btsbd.com',
    address: 'Shawnil-4, Safeway Complex (3rd Floor), Mirjajangal, Sylhet',
    status: StatusType.ACTIVE,
    createdAt: new Date('2023-02-25'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-100',
    name: 'Stardust Telecom Ltd.',
    type: CompanyType.ISP,
    email: 'info@stardusttelecom.com',
    address: '18th Floor, Awal Center, 34, Kamal Ataturk Avenue, Banani C/A, Dhaka-1213.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2023-02-26'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-101',
    name: 'HN Telecom Limited',
    type: CompanyType.ISP,
    email: 'info@hntelecom.com.bd',
    address: 'Usman House (2nd Floor), Ray Bahadur Road, Jalesharitola, Bogra-5800.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2018-02-26'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-102',
    name: 'Mango Teleservices Limited',
    type: CompanyType.ISP,
    email: 'contact@mango.com.bd',
    address: '82, Bir Uttam, Mohakhali C/A, 12th Floor, Dhaka-1212',
    status: StatusType.ACTIVE,
    createdAt: new Date('2018-10-13'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-103',
    name: 'X-Net Limited',
    type: CompanyType.ISP,
    email: 'info@xnet.com.bd',
    address: 'Suite # 1103, Concord Tower, 113 Kazi Nazrul Islam Avenue, Dhaka-1000.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2022-02-28'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-104',
    name: 'M/s. Comilla Online',
    type: CompanyType.ISP,
    email: 'info@comillaonline.com.bd',
    address: '333, Jhawtala (Ground floor), Comilla-3500',
    status: StatusType.ACTIVE,
    createdAt: new Date('2019-11-19'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-105',
    name: 'M/s. IDS Bangladesh',
    type: CompanyType.ISP,
    email: 'info@idsbd.com',
    address: '42, Kemal Ataturk Avenue (Iqbal Centre) 5th Floor, Banani, Dhaka-1213.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2021-06-21'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-106',
    name: 'Daffodil Online Limited',
    type: CompanyType.ISP,
    email: 'info@daffodil.net',
    address: '64/3 Lake Circuse, Kalabagan, Dhaka-1205',
    status: StatusType.ACTIVE,
    createdAt: new Date('2021-10-23'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-107',
    name: 'M/s. Grameen Communications',
    type: CompanyType.ISP,
    email: 'info@grameen.org',
    address: 'Telecom Bhaban (Level-7), 53/1 Box Nagar, Zoo Road, Mirpur-1, Dhaka-1216',
    status: StatusType.ACTIVE,
    createdAt: new Date('2021-01-18'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-108',
    name: 'ICON Infotech Limited',
    type: CompanyType.ISP,
    email: 'info@iconinfotech.com',
    address: 'PFI Tower (4th floor), 56-57 Dilkusha C/A, Dhaka-1000',
    status: StatusType.ACTIVE,
    createdAt: new Date('2020-07-13'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-109',
    name: 'Infocom Limited',
    type: CompanyType.ISP,
    email: 'info@infocom.com.bd',
    address: 'Shama, Batali Hills, Chittagong',
    status: StatusType.ACTIVE,
    createdAt: new Date('2019-04-30'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-110',
    name: 'Manor IT Limited',
    type: CompanyType.ISP,
    email: 'info@manorit.com',
    address: 'Level-5, Galleria Shopping and Apartment Complex, Zindabazar, Sylhet',
    status: StatusType.ACTIVE,
    createdAt: new Date('2021-09-26'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-111',
    name: 'Winer Communication',
    type: CompanyType.ISP,
    email: 'info@winercomm.com',
    address: 'Suite#.2 (11th floor), Eastern View, 50 DIT Extension Road, Dhaka-1000',
    status: StatusType.ACTIVE,
    createdAt: new Date('2020-01-05'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-112',
    name: 'Prisma Digital Network Limited',
    type: CompanyType.ISP,
    email: 'info@prismadigital.com',
    address: '155/A, Gulshan Avenue, Gulshan-2, Dhaka-1212',
    status: StatusType.ACTIVE,
    createdAt: new Date('2021-09-22'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-113',
    name: 'HRC Technologies Limited',
    type: CompanyType.ISP,
    email: 'info@hrctech.com',
    address: '26 Shamoly (2nd floor) Bir Uttam A.W, Chowdhury Road, Dhaka-1207',
    status: StatusType.ACTIVE,
    createdAt: new Date('2021-09-19'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-114',
    name: 'M/s. InComIT Solution',
    type: CompanyType.ISP,
    email: 'info@incomit.com',
    address: '52, New Eskaton Road, TMC Building (6th floor), Dhaka-1000.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2020-07-13'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-115',
    name: 'Orange Communication',
    type: CompanyType.ISP,
    email: 'info@orangecommunication.com.bd',
    address: '220/1, Road- Begum Rokeya Sharani, Taltola, West Kafrul, Dhaka-1207 367 kazipara 9ground floor)kafrul, dhaka-1216.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2014-09-22'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-116',
    name: 'GramBangla Systems Limited',
    type: CompanyType.ISP,
    email: 'info@grambanglasystems.com',
    address: '14th Floor, Grameen Bank Bhaban, Mirpur-2, Dhaka-1216',
    status: StatusType.ACTIVE,
    createdAt: new Date('2020-06-21'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-117',
    name: 'Stargate Communications Limited',
    type: CompanyType.ISP,
    email: 'info@stargatebd.com',
    address: '52/1, Hasan Holdings (3rd Floor), New Eskaton Road, Dhaka-1000',
    status: StatusType.ACTIVE,
    createdAt: new Date('2019-08-03'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-118',
    name: 'Tomato Web (Pvt.) Limited',
    type: CompanyType.ISP,
    email: 'info@tomatoweb.com',
    address: 'Motaleb Tower, 8/2 Paribagh, Suite#A (2nd Floor), Dhaka-1000',
    status: StatusType.ACTIVE,
    createdAt: new Date('2016-02-14'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-119',
    name: 'Weblink Communication Limited',
    type: CompanyType.ISP,
    email: 'info@weblinkbd.com',
    address: '1st Floor, Sarkar Super Complex Bazar Road, Mawna Chowrasta, Sreepur, Gazipur.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2021-06-28'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-120',
    name: 'Bangladesh Bank',
    type: CompanyType.ISP,
    email: 'bb.governor@bb.org.bd',
    address: 'Head Office, Motijheel, Dhaka-1000.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2016-12-08'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-121',
    name: 'Bangladesh Telecommunication Company Limited (BTCL)',
    type: CompanyType.ISP,
    email: 'md@btcl.gov.bd',
    address: 'Telejogajog Bhaban, 37/E, Eskaton Garden, Dhaka-1000',
    status: StatusType.ACTIVE,
    createdAt: new Date('2018-03-25'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-122',
    name: 'Bismillah Telecom Service',
    type: CompanyType.ISP,
    email: 'info@bismillahtelecom.com',
    address: '268, Nababpur Road, Nababpur Complex, Dhaka',
    status: StatusType.ACTIVE,
    createdAt: new Date('2023-01-08'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-123',
    name: 'Business Zone Limited',
    type: CompanyType.ISP,
    email: 'info@businesszone.com',
    address: 'Level-5, Holding-3, Road-4, Block-F, Banani, Dhaka1213',
    status: StatusType.ACTIVE,
    createdAt: new Date('2016-12-15'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-124',
    name: 'Communication One (Pvt) Ltd.',
    type: CompanyType.ISP,
    email: 'info@commone.com',
    address: '170/A, Bara magh bazar, Outer circular Road, Dhaka-1217',
    status: StatusType.ACTIVE,
    createdAt: new Date('2014-09-20'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-125',
    name: 'Red Data (Pvt.) Limited',
    type: CompanyType.ISP,
    email: 'info@reddatabd.com',
    address: 'H#16. R#3, Lane-4, Block-K, Halishahar Housing State, Halishahar, Chittagong.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2022-09-17'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-126',
    name: 'M/s. Sajid Trading',
    type: CompanyType.ISP,
    email: 'info@sajidtrading.com',
    address: 'Vanga Town, Vanga, Faridpur.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2016-03-06'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-127',
    name: 'Siam Trading',
    type: CompanyType.ISP,
    email: 'info@siamtrading.com.bd',
    address: 'D-3, 26 Eskaton Garden, Ramna, Dhaka-1000.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2023-02-15'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-128',
    name: 'Sustainable Development Networking Foundation (SDNF)',
    type: CompanyType.ISP,
    email: 'info@sdnfbd.org',
    address: 'Firoz Tower, 13th Floor, 152/3-B, Panthapath, Green Road, Dhaka',
    status: StatusType.ACTIVE,
    createdAt: new Date('2023-02-06'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-129',
    name: 'Telebangla Communication Ltd.',
    type: CompanyType.ISP,
    email: 'info@telebanglabd.com',
    address: 'Section-12, Block-B, Road-61/1, 61/2, Pallabi, Mirpur, Dhaka-1216',
    status: StatusType.ACTIVE,
    createdAt: new Date('2017-04-15'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-130',
    name: 'University Grants Commission of Bangladesh',
    type: CompanyType.ISP,
    email: 'ugc@ugc.gov.bd',
    address: 'Agargaon, Dhaka-1207',
    status: StatusType.ACTIVE,
    createdAt: new Date('2020-07-25'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-131',
    name: 'X-Link Limited',
    type: CompanyType.ISP,
    email: 'info@xlink.com',
    address: '57/12 West Panthapath, Shonargaon Plaza, (4th floor), Dhaka-1215',
    status: StatusType.ACTIVE,
    createdAt: new Date('2013-11-11'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-132',
    name: 'Abuzz IT Limited',
    type: CompanyType.ISP,
    email: 'info@abuzzit.com',
    address: 'House-83, Road-8/A, 4th Floor, Keari Plaza, Dhanmondi, Dhaka-1209.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2018-01-21'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-133',
    name: 'Asia Tel Network Ltd.',
    type: CompanyType.ISP,
    email: 'info@asiatel.com',
    address: '14, Purana Paltan, Dhaka-1000',
    status: StatusType.ACTIVE,
    createdAt: new Date('2008-08-11'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-134',
    name: 'M/s. BK Online',
    type: CompanyType.ISP,
    email: 'info@bkonline.com',
    address: '47 Khanjahan Ali Road, Khulna-9100.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2010-07-13'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-135',
    name: 'Bright Technologies Limited',
    type: CompanyType.ISP,
    email: 'info@brighttechbd.com',
    address: 'Flat-D7, House: 418, Kuwaiti Mosque Road, Vatara, Dhaka-1229.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2019-08-26'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-136',
    name: 'Ergo Ventures Pvt. Limited',
    type: CompanyType.ISP,
    email: 'info@ergoventures.com',
    address: 'Mir Noor Square, H#43, R#2/A, Dhanmondi R/A, Dhaka.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-12-30'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-137',
    name: 'Genex Infosys Limited',
    type: CompanyType.ISP,
    email: 'info@genexinfosys.com',
    address: 'House#09, Road#25/A, Block-A, Banani, Dhaka-1213',
    status: StatusType.ACTIVE,
    createdAt: new Date('2018-03-11'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-138',
    name: 'Hello Tech Limited',
    type: CompanyType.ISP,
    email: 'info@hellotechbd.com',
    address: '26/1, Green Road (1/C, Green Corner), 2nd Floor, Dhaka-1205',
    status: StatusType.ACTIVE,
    createdAt: new Date('2018-02-15'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-139',
    name: 'Virtual American Companies (BD) Limited',
    type: CompanyType.ISP,
    email: 'info@virtualamericabd.com',
    address: 'First Floor, 67/D, North Dhanmondi, Kalabagan, Dhaka-1205.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2012-09-17'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-140',
    name: 'Vision Technologies Limited',
    type: CompanyType.ISP,
    email: 'info@visiontech.com.bd',
    address: 'Square Centre, 48 Bir Uttam A. K. Khandaker Road, Mohakhali C/A, Dhaka-1212.',
    status: StatusType.ACTIVE,
    createdAt: new Date('2023-03-05'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-141',
    name: 'Bangladesh Computer Council (BCC)',
    type: CompanyType.ISP,
    email: 'info@bcc.gov.bd',
    address: 'ICT Tower, Plot E-14/X, Agargaon, Sher-E-Bangla Nagar, Dhaka',
    status: StatusType.ACTIVE,
    createdAt: new Date('2023-11-29'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-142',
    name: 'Delta Software and Communication Limited',
    type: CompanyType.ISP,
    email: 'info@deltasoftbd.com',
    address: 'Basati Horizon Suit No. 16/b, Plot No-21, Road No-17, Banani C/A, Dhaka-1213',
    status: StatusType.ACTIVE,
    createdAt: new Date('2013-10-10'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'comp-143',
    name: 'Asia Intel Communications',
    type: CompanyType.ISP,
    email: 'info@asiaintel.com',
    address: '72, Helena Monjil, Outer Circular Road, Boro Mogbazar, Dhaka-1217',
    status: StatusType.ACTIVE,
    createdAt: new Date('2011-10-10'),
    updatedAt: new Date('2024-06-12'),
  },
];

// Mock Cache Providers Data
export const mockCacheProviders: CacheProvider[] = [
  {
    id: 'cp-001',
    name: 'FastNet Access',
    shortCode: 'FNA',
    description: 'Content delivery network for Asia-Pacific region',
    status: StatusType.ACTIVE,
    serverCount: 0,
    totalCapacity: 0,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 'cp-002',
    name: 'Global Global Cache',
    shortCode: 'GGC',
    description: 'Worldwide edge caching solution',
    status: StatusType.ACTIVE,
    serverCount: 0,
    totalCapacity: 0,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 'cp-003',
    name: 'BaisanCloud',
    shortCode: 'BaisanCloud',
    description: 'Cloud-based caching infrastructure',
    status: StatusType.ACTIVE,
    serverCount: 0,
    totalCapacity: 0,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-06-08'),
  },
  {
    id: 'cp-004',
    name: 'BIGO Cache Network',
    shortCode: 'BIGO',
    description: 'Video streaming and live broadcast caching',
    status: StatusType.ACTIVE,
    serverCount: 0,
    totalCapacity: 0,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'cp-005',
    name: 'Cloudflare Edge',
    shortCode: 'Cloudflare',
    description: 'Global content delivery and security',
    status: StatusType.ACTIVE,
    serverCount: 0,
    totalCapacity: 0,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-06-05'),
  },
  {
    id: 'cp-006',
    name: 'Zenlayer Platform',
    shortCode: 'Zenlayer',
    description: 'Multi-cloud connectivity and caching',
    status: StatusType.ACTIVE,
    serverCount: 0,
    totalCapacity: 0,
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-06-11'),
  },
  {
    id: 'cp-007',
    name: 'G-Core Labs',
    shortCode: 'G-Core Labs',
    description: 'Advanced DDoS protection and CDN',
    status: StatusType.ACTIVE,
    serverCount: 0,
    totalCapacity: 0,
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-06-09'),
  },
  {
    id: 'cp-008',
    name: 'Tencent Cloud CDN',
    shortCode: 'Tencent',
    description: 'Chinese market CDN and caching',
    status: StatusType.ACTIVE,
    serverCount: 0,
    totalCapacity: 0,
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-05-25'),
  },
  {
    id: 'cp-009',
    name: 'Netflix CDN',
    shortCode: 'Netflix',
    description: 'Video streaming cache service',
    status: StatusType.ACTIVE,
    serverCount: 0,
    totalCapacity: 0,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 'cp-010',
    name: 'CDN77 Edge',
    shortCode: 'CDN77',
    description: 'High performance CDN provider',
    status: StatusType.ACTIVE,
    serverCount: 0,
    totalCapacity: 0,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 'cp-011',
    name: 'MCC Cache',
    shortCode: 'MCC',
    description: 'Mobile connection cache server',
    status: StatusType.ACTIVE,
    serverCount: 0,
    totalCapacity: 0,
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 'cp-012',
    name: 'Akamai Edge',
    shortCode: 'Akamai',
    description: 'Global content delivery network',
    status: StatusType.ACTIVE,
    serverCount: 0,
    totalCapacity: 0,
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-06-10'),
  },
];

// Mock Servers Data
export const mockServers: Server[] = [
  {
    id: 'srv-001',
    name: 'Cache-Server-01-DEL',
    model: 'HP',
    brand: 'HP',
    totalCapacityGB: 5000,
    usedCapacityGB: 4200,
    location: 'Delhi - Rack A1',
    rackNumber: 'A1-12',
    ipAddress: '192.168.1.10',
    status: StatusType.ACTIVE,
    notes: 'Primary cache server for Delhi region',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 'srv-002',
    name: 'Cache-Server-02-DEL',
    model: 'HP',
    brand: 'HP',
    totalCapacityGB: 5000,
    usedCapacityGB: 3800,
    location: 'Delhi - Rack A2',
    rackNumber: 'A2-08',
    ipAddress: '192.168.1.11',
    status: StatusType.ACTIVE,
    notes: 'Secondary cache server for Delhi region',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-06-09'),
  },
  {
    id: 'srv-003',
    name: 'Cache-Server-01-MUM',
    model: 'DELL 730',
    brand: 'Dell',
    totalCapacityGB: 8000,
    usedCapacityGB: 6500,
    location: 'Mumbai - Rack B1',
    rackNumber: 'B1-15',
    ipAddress: '192.168.2.10',
    status: StatusType.ACTIVE,
    notes: 'High-capacity server for Mumbai operations',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-06-11'),
  },
  {
    id: 'srv-004',
    name: 'Cache-Server-01-BNG',
    model: 'DELL 830',
    brand: 'Dell',
    totalCapacityGB: 6000,
    usedCapacityGB: 2100,
    location: 'Bangalore - Rack C1',
    rackNumber: 'C1-20',
    ipAddress: '192.168.3.10',
    status: StatusType.ACTIVE,
    notes: 'New server with available capacity',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-06-08'),
  },
  {
    id: 'srv-005',
    name: 'Cache-Server-01-HYD',
    model: 'HP',
    brand: 'HP',
    totalCapacityGB: 4000,
    usedCapacityGB: 3950,
    location: 'Hyderabad - Rack D1',
    rackNumber: 'D1-05',
    ipAddress: '192.168.4.10',
    status: StatusType.ACTIVE,
    notes: 'Nearly full capacity - monitor closely',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'srv-006',
    name: 'Cache-Server-BACKUP',
    model: 'HP',
    brand: 'HP',
    totalCapacityGB: 3000,
    usedCapacityGB: 500,
    location: 'Pune - Rack E1',
    rackNumber: 'E1-01',
    ipAddress: '192.168.5.10',
    status: StatusType.PENDING,
    notes: 'Backup server - pending activation',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-05-20'),
  },
  {
    id: 'srv-007',
    name: 'Cache-Server-01-CHN',
    model: 'DELL 730',
    brand: 'Dell',
    totalCapacityGB: 10000,
    usedCapacityGB: 7200,
    location: 'Chennai - Rack F1',
    rackNumber: 'F1-25',
    ipAddress: '192.168.6.10',
    status: StatusType.INACTIVE,
    notes: 'Decommissioned - not in use',
    createdAt: new Date('2023-12-01'),
    updatedAt: new Date('2024-04-15'),
  },
];

// Mock Allocations Data
export const mockAllocations: Allocation[] = [];

// Helper function to get data
export const getCompanies = (): Company[] => mockCompanies;
export const getCacheProviders = (): CacheProvider[] => mockCacheProviders;
export const getServers = (): Server[] => mockServers;
export const getAllocations = (): Allocation[] => mockAllocations;

// Helper function to find by ID
export const getCompanyById = (id: string): Company | undefined => {
  return mockCompanies.find(c => c.id === id);
};

export const getCacheProviderById = (id: string): CacheProvider | undefined => {
  return mockCacheProviders.find(cp => cp.id === id);
};

export const getServerById = (id: string): Server | undefined => {
  return mockServers.find(s => s.id === id);
};

export const getAllocationById = (id: string): Allocation | undefined => {
  return mockAllocations.find(a => a.id === id);
};
